baseURL = "https://elkcityhazard.github.io/arbor-house/"
languageCode = "en-us"
theme = "memorycare"
title = "Arbor House"
[params]
  description = "Adult Foster Care and Memory Care In Traverse City, Michigan"
  subtitle = "Adult Foster Care Traverse City, Michigan"
[menu]

  [[menu.main]]
    identifier = "about"
    name = "About Us"
    url = "/about/"
    weight = -110

 # [[menu.main]]
 #   identifier = "services"
 #   name = "Services"
 #   url = "/services/"
 #   weight = -100

  [[menu.main]]
    identifier = "memory care"
    name = "Memory Care"
    parent = "Services"
    url = "/services/traverse-city-memory-care"
    weight = -100

  [[menu.main]]
    identifier = "dementia care"
    name = "Dementia Care"
    parent = "Services"
    url = "/services/traverse-city-dementia-care"
    weight = -100

  [[menu.main]]
    identifier = "faq"
    name = "FAQs"
    url = "/faqs/"
    weight = -100


