baseURL = "https://elkcityhazard.github.io/arbor-house/"
languageCode = "en-us"
theme = "memorycare"
title = "Arbor House Nursing Home, Alzheimer's Care, Dementia Care, Traverse City, Michigan"
[params]
  description = "Arbor House Assisted Living home specializes in providing total care for seniors with memory loss, alzheimer's care and dementia care."
  subtitle = "Adult Foster Care Traverse City, Michigan"
  
[menu]

  [[menu.main]]
    identifier = "about"
    name = "About Us"
    url = "/about/"
    weight = -110

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = -100

    [[menu.main]]
    identifier = "faq"
    name = "FAQs"
    url = "/faqs/"
    weight = -100
  
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = -110
  
  [[menu.mobile]]
    identifier = "about"
    name = "About Us"
    url = "/about/"
    weight = -110

  [[menu.mobile]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = -110
  

  [[menu.mobile]]
    identifier = "memory care traverse city"
    name = "Memory Care"
    parent = "Services"
    url = "/services/memory-care-traverse-city"
    weight = -100

  [[menu.mobile]]
    identifier = "dementia care traverse city"
    name = "Dementia Care"
    parent = "Services"
    url = "/services/dementia-care-traverse-city"
    weight = -100

  [[menu.mobile]]
    identifier = "assisting-living-traverse-city"
    name = "Assisted Living"
    parent = "Services"
    url = "/services/assisted-living-traverse-city"
    weight = -100
  
  [[menu.mobile]]
    identifier = "nursing-home-traverse-city"
    name = "Nursing Home"
    parent = "Services"
    url = "/services/nursing-home-traverse-city"
    weight = -100

  [[menu.mobile]]
    identifier = "faq"
    name = "FAQs"
    url = "/faqs/"
    weight = -100

