baseURL = "https://localhost:1313/"
languageCode = "en-us"
theme = "memorycare"
[params]
  description = "Arbor house is an assisted living home in Traverse City, Michigan that specializes in demential and Alzheimer's Disease."
  subtitle = "Assisted Living Home Traverse City, Michigan"


  



