baseURL = "https://localhost:1313/"
languageCode = "en-us"
theme = "memorycare"
[params]
  description = "Adult Foster Care and Memory Care In Traverse City, Michigan"
  subtitle = "Adult Foster Care Traverse City, Michigan"


  



